### ISSUE TITLE
Error while using itemstack_in_inventory

### ISSUE THREAD

**Issue by GJSteve20** [EnvyWare/ForgeMenus#16]
I've tried your example code for itemstack in inventory and I got the following error:

Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_184429_b(Lnet/minecraft/item/ItemStack;)I
        at com.envyful.menus.forge.data.impl.ItemInInventoryRequirement.fits(ItemInInventoryRequirement.java:37) ~[ItemInInventoryRequirement.class:?]
        at com.envyful.menus.forge.data.ConfigItem.canSee(ConfigItem.java:160) ~[ConfigItem.class:?]
        at com.envyful.menus.forge.data.ConfigItem.build(ConfigItem.java:98) ~[ConfigItem.class:?]
        at com.envyful.menus.forge.ui.GenericUI.placeElements(GenericUI.java:122) ~[GenericUI.class:?]

![image](https://user-images.githubusercontent.com/44862419/167266597-145ce884-a34a-4058-affc-d39ac1ec3759.png)

**Comment by danorris709** [comment]
You've not provided enough information.
I need what the name of the Jar you've used is, the Minecraft version, and what mods/mixins you've got loaded.
